//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisQuejasReclamos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuejasDBEntities1 : DbContext
    {
        public QuejasDBEntities1()
            : base("name=QuejasDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Departamento> Departamentos { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<EstadoG> EstadoGs { get; set; }
        public virtual DbSet<EstadoPersonal> EstadoPersonals { get; set; }
        public virtual DbSet<EstadoQR> EstadoQRs { get; set; }
        public virtual DbSet<Privilegio> Privilegios { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Queja> Quejas { get; set; }
        public virtual DbSet<Reclamo> Reclamos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipoQueja> TipoQuejas { get; set; }
        public virtual DbSet<TipoReclamo> TipoReclamoes { get; set; }
        public virtual DbSet<UsuariosLogin> UsuariosLogins { get; set; }
    }
}
