//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisQuejasReclamos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queja
    {
        public int Id_Queja { get; set; }
        public int Id_Cliente { get; set; }
        public int Id_TipoQueja { get; set; }
        public int Id_Producto { get; set; }
        public int Id_Departamento { get; set; }
        public int Id_Empleado { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_EstadoQR { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual EstadoQR EstadoQR { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual TipoQueja TipoQueja { get; set; }
    }
}
