//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisQuejasReclamos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosLogin
    {
        public int IdUsuarioL { get; set; }
        public string UsuarioL { get; set; }
        public string Contrasena { get; set; }
        public int Id_Privilegio { get; set; }
        public int Id_EstadoG { get; set; }
    
        public virtual EstadoG EstadoG { get; set; }
        public virtual Privilegio Privilegio { get; set; }
    }
}
